apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: magnushackathon
  namespace: magnusargocd
spec:
  project: default
  source:
    repoURL: https://github.com/magnuscowie/bootcamp.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: magnus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
