apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: manusdatabase
  namespace: magnushackathon
spec:
  serviceName: "database"
  replicas: 1
  selector:
    matchLabels:
      app: magnusdb
  template:
    metadata:
      labels:
        app: magnusdb
    spec:
      containers:
        - name: db
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              vaule: "hackanton"
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
