apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magnushack-ingress
  namespace: magnushackathon
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: myapplocalhack.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
